# Site
repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Sebastian Gustavsson
title: Computer Engineering Master's student
email: sebastian@gustavsson.tech
website: www.gustavsson.tech

# Social links
# twitter_username: facespics
github_username: Ziron
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: sebastian-gustavsson-827448135
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Sebastian and I'm a Computer Engineering Master's student. As well as studying I also do freelance work as a full stack developer. I am also engaged in a number of student associations where I get to do many cool projects.

  I am most skilled in: <mark>Python</mark> and <mark>C++</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in electronics and software engineering some of my other interests and hobbies are:
   - Sailing
   - 3D printing
   - Mechanics
   
# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
